# generated by datamodel-codegen:
#   filename:  id.json
#   timestamp: 2022-01-29T10:28:48+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel


class AdditionalParameters(BaseModel):
    membershipType: int
    membershipId: str


class ID(BaseModel):
    platformId: int
    platformSlug: str
    platformUserIdentifier: str
    platformUserId: Any
    platformUserHandle: str
    avatarUrl: Any
    status: Any
    additionalParameters: AdditionalParameters
