# generated by datamodel-codegen:
#   filename:  pvpseason.json
#   timestamp: 2022-01-29T11:41:57+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Attributes(BaseModel):
    playlist: str
    group: str
    season: int


class Metadata(BaseModel):
    name: str
    imageUrl: str
    imageBackground: str


class IconUrl(BaseModel):
    value: str
    displayValue: str


class RankColor(BaseModel):
    value: str
    displayValue: str


class Metadata1(BaseModel):
    key: str
    iconUrl: IconUrl
    rankColor: RankColor
    rankName: str


class Elo(BaseModel):
    rank: int
    percentile: float
    displayName: str
    displayCategory: Any
    category: str
    metadata: Metadata1
    value: int
    displayValue: str
    displayType: str


class Metadata2(BaseModel):
    key: str


class ActivitiesWon(BaseModel):
    rank: Any
    percentile: Any
    displayName: str
    displayCategory: Any
    category: str
    metadata: Metadata2
    value: int
    displayValue: str
    displayType: str


class Metadata3(BaseModel):
    key: str


class ActivitiesPlayed(BaseModel):
    rank: Any
    percentile: Any
    displayName: str
    displayCategory: Any
    category: str
    metadata: Metadata3
    value: int
    displayValue: str
    displayType: str


class Metadata4(BaseModel):
    key: str


class ActivitiesLost(BaseModel):
    rank: Any
    percentile: Any
    displayName: str
    displayCategory: Any
    category: str
    metadata: Metadata4
    value: int
    displayValue: str
    displayType: str


class Metadata5(BaseModel):
    key: str


class Wl(BaseModel):
    rank: Any
    percentile: Any
    displayName: str
    displayCategory: Any
    category: str
    metadata: Metadata5
    value: float
    displayValue: str
    displayType: str


class Metadata6(BaseModel):
    key: str


class Kills(BaseModel):
    rank: Any
    percentile: Any
    displayName: str
    displayCategory: Any
    category: str
    metadata: Metadata6
    value: int
    displayValue: str
    displayType: str


class Metadata7(BaseModel):
    key: str


class Deaths(BaseModel):
    rank: Any
    percentile: Any
    displayName: str
    displayCategory: Any
    category: str
    metadata: Metadata7
    value: int
    displayValue: str
    displayType: str


class Metadata8(BaseModel):
    key: str


class Kd(BaseModel):
    rank: Any
    percentile: Any
    displayName: str
    displayCategory: Any
    category: str
    metadata: Metadata8
    value: float
    displayValue: str
    displayType: str


class Metadata9(BaseModel):
    key: str


class Kad(BaseModel):
    rank: Any
    percentile: Any
    displayName: str
    displayCategory: Any
    category: str
    metadata: Metadata9
    value: float
    displayValue: str
    displayType: str


class Metadata10(BaseModel):
    key: str


class Kda(BaseModel):
    rank: Any
    percentile: Any
    displayName: str
    displayCategory: Any
    category: str
    metadata: Metadata10
    value: float
    displayValue: str
    displayType: str


class Metadata11(BaseModel):
    key: str


class Assists(BaseModel):
    rank: Any
    percentile: Any
    displayName: str
    displayCategory: Any
    category: str
    metadata: Metadata11
    value: int
    displayValue: str
    displayType: str


class Metadata12(BaseModel):
    key: str


class KillsPga(BaseModel):
    rank: Any
    percentile: Any
    displayName: str
    displayCategory: Any
    category: str
    metadata: Metadata12
    value: float
    displayValue: str
    displayType: str


class Stats(BaseModel):
    elo: Elo
    activitiesWon: ActivitiesWon
    activitiesPlayed: ActivitiesPlayed
    activitiesLost: ActivitiesLost
    wl: Wl
    kills: Kills
    deaths: Deaths
    kd: Kd
    kad: Kad
    kda: Kda
    assists: Assists
    killsPga: KillsPga


class PVPSeason(BaseModel):
    type: str
    attributes: Attributes
    metadata: Metadata
    expiryDate: str
    stats: Stats
